apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nginx-reverse-proxy
  name: nginx-reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: nginx-reverse-proxy
    spec:
      containers:
      - image: adnicolae/reverse-proxy-docker-kube
        name: nginx-reverse-proxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always